import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarServer from "./components/NavbarServer";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digitalisation des bons de travaux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarServer />
        <Toaster richColors />
        {children}
        
      </body>
    </html>
  );
}
